// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "news_service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewsUseCase is an autogenerated mock type for the NewsUseCase type
type NewsUseCase struct {
	mock.Mock
}

// CreateNews provides a mock function with given fields: ctx, title, content
func (_m *NewsUseCase) CreateNews(ctx context.Context, title string, content string) (*domain.News, error) {
	ret := _m.Called(ctx, title, content)

	if len(ret) == 0 {
		panic("no return value specified for CreateNews")
	}

	var r0 *domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.News, error)); ok {
		return rf(ctx, title, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.News); ok {
		r0 = rf(ctx, title, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, title, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNews provides a mock function with given fields: ctx, id
func (_m *NewsUseCase) DeleteNews(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNews")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllNews provides a mock function with given fields: ctx, page, limit
func (_m *NewsUseCase) GetAllNews(ctx context.Context, page int, limit int) ([]*domain.News, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllNews")
	}

	var r0 []*domain.News
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.News, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*domain.News); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetNewsByID provides a mock function with given fields: ctx, id
func (_m *NewsUseCase) GetNewsByID(ctx context.Context, id string) (*domain.News, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNewsByID")
	}

	var r0 *domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.News, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.News); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchNews provides a mock function with given fields: ctx, query, page, limit
func (_m *NewsUseCase) SearchNews(ctx context.Context, query string, page int, limit int) ([]*domain.News, int64, error) {
	ret := _m.Called(ctx, query, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchNews")
	}

	var r0 []*domain.News
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.News, int64, error)); ok {
		return rf(ctx, query, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.News); ok {
		r0 = rf(ctx, query, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, query, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, query, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateNews provides a mock function with given fields: ctx, id, title, content
func (_m *NewsUseCase) UpdateNews(ctx context.Context, id string, title string, content string) (*domain.News, error) {
	ret := _m.Called(ctx, id, title, content)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNews")
	}

	var r0 *domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.News, error)); ok {
		return rf(ctx, id, title, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.News); ok {
		r0 = rf(ctx, id, title, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, id, title, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNewsUseCase creates a new instance of NewsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNewsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *NewsUseCase {
	mock := &NewsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
